/*
SELECT ATTRIBUTE LIST
FROM RELATION NAMES
WHERE CONDITION.
*/

SELECT E.Address FROM
(SELECT * FROM EMPLOYEE) AS E;

-- EXISTS AND NOT EXISTS?
SELECT *
FROM EMPLOYEE E WHERE EXISTS (SELECT * FROM EMPLOYEE E2 WHERE E.FName = E2.Fname AND E.Ssn <> E2.Ssn);

SELECT * FROM EMPLOYEE
WHERE [Address] IS NULL;

SELECT * FROM EMPLOYEE
WHERE [Address] IS NOT NULL;

SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;
-- BOOLEAN EQUALITY, TRUE, FALSE, UNKNOWN
-- Get the department that each employee manages i.e. employee name, and their department.
SELECT FName, MInit, LName, Name FROM EMPLOYEE
INNER JOIN DEPARTMENT
ON Ssn = ManagerSsn;

-- Get the employees who aren't managers. i.e. employee name.
SELECT FName, MInit, LName, DEPARTMENT.Name FROM EMPLOYEE
LEFT OUTER JOIN DEPARTMENT
ON Ssn = ManagerSsn
WHERE DEPARTMENT.NAME IS NULL;

-- How many tuples does the relation have.
SELECT COUNT(*) FROM EMPLOYEE; -- COUNT()

-- What is the average salary of all employees?
SELECT AVG(Salary) FROM EMPLOYEE;

-- SELECT SUM(Salary) FROM EMPLOYEE;

-- Write me a SQL statement to get me the average salary without using AVG function? *
SELECT SUM(Salary) / COUNT(1) FROM EMPLOYEE;

SELECT MIN(Salary) FROM EMPLOYEE;

SELECT MAX(Salary) FROM EMPLOYEE;

SELECT [Name], COUNT(1) FROM EMPLOYEE
INNER JOIN DEPARTMENT
ON Ssn = ManagerSsn
GROUP BY [Name];

SELECT * FROM EMPLOYEE;

SELECT * FROM PROJECT;
/*INSERT INTO PROJECT VALUES (1, 'DATABASE DESIGN PROJECT', 'UNIVERSITY OF MONTANA');
INSERT INTO PROJECT VALUES (2, 'CONSTRUCTION PROJECT', 'UNIVERSITY OF MONTANA');*/

SELECT * FROM WORKSON;

INSERT INTO WORKSON
SELECT Ssn, 1, 40.00
FROM EMPLOYEE WHERE Salary <= 1.00;

-- HOW MANY EMPLOYEES WORK ON EACH PROJECT?
SELECT P.Name, E.FName, COUNT(1), AVG(E.Salary) FROM PROJECT P
INNER JOIN WORKSON W
ON P.Number = W.ProjectNumber
INNER JOIN EMPLOYEE E
ON W.EmployeeSsn = E.Ssn
GROUP BY P.Name, E.FName
-- HAVING AVG(E.Salary) > 1.00;

/*
SELECT ATTRIBUTE LIST
FROM RELATION(S)
JOINS
WHERE
GROUP BY
HAVING
ORDER BY
*/

SELECT * FROM DEPARTMENT WHERE Number = 1