CREATE TABLE PROJECT
(
    [Number] INT CONSTRAINT PK_PROJECT_NUMBER PRIMARY KEY,
    [Name] VARCHAR(100) NOT NULL CONSTRAINT UN_PROJECT_NAME UNIQUE,
    [Location] VARCHAR(100) NOT NULL CONSTRAINT DF_PROJECT_LOCATION DEFAULT 'N/A'
);

CREATE TABLE WORKSON
(
    EmployeeSsn SSN_TYPE NOT NULL CONSTRAINT FK_WORKSON_EMPLOYEESSN FOREIGN KEY REFERENCES EMPLOYEE(Ssn) ON DELETE CASCADE,
    ProjectNumber INT NOT NULL CONSTRAINT FK_WORKSON_PROJECTNUMBER FOREIGN KEY REFERENCES PROJECT(Number) ON DELETE CASCADE,
    [Hours] DECIMAL(5, 2) NOT NULL CONSTRAINT CK_WORKSON_HOURS CHECK ([Hours] > 0)
);

ALTER TABLE WORKSON
ADD CONSTRAINT PK_WORKSON_EMPLOYEESSN_PROJECTNUMBER
PRIMARY KEY (EmployeeSsn, ProjectNumber);

SELECT *
FROM EMPLOYEE
WHERE [Address] IS NOT NULL;

SELECT *
FROM EMPLOYEE
WHERE [Address] IS NULL;

-- JIM, JAMES, JILL
SELECT * FROM EMPLOYEE
WHERE FName = 'JIM'
OR FName = 'JAMES'
OR FName = 'JILL';

SELECT * FROM EMPLOYEE
WHERE FName IN ('JIM', 'JAMES', 'JILL');

SELECT * FROM EMPLOYEE
-- WHERE FName LIKE 'J%';

SELECT * FROM EMPLOYEE
WHERE Ssn IN (SELECT DISTINCT ManagerSsn FROM DEPARTMENT);

SELECT * FROM DEPARTMENT;

INSERT INTO DEPARTMENT VALUES (2, 'Journalism', '123456789', GETDATE());

-- EXISTS OR NOT EXISTS.
SELECT * FROM
EMPLOYEE E WHERE NOT EXISTS (SELECT * FROM EMPLOYEE E2 WHERE E.Fname = E2.Fname AND E.Ssn <> E2.Ssn);

-- UPDATE EMPLOYEE SET Fname = 'JIM' WHERE FName = 'Beardy';

SELECT * FROM EMPLOYEE;

SELECT * FROM DEPARTMENT;

SELECT * FROM
EMPLOYEE E
INNER JOIN
DEPARTMENT D
ON E.Ssn = D.ManagerSsn;

SELECT * FROM
EMPLOYEE E
LEFT OUTER JOIN
DEPARTMENT D
ON E.Ssn = D.ManagerSsn;

SELECT * FROM
DEPARTMENT D
LEFT OUTER JOIN
EMPLOYEE E
ON E.Ssn = D.ManagerSsn;