CREATE TABLE DEPARTMENT
(
    -- ATTRIBUTE NAME ATTRIBUTE TYPE CONSTRAINT(S)
    [Number] SMALLINT CONSTRAINT PK_DEPARTMENT_NUMBER PRIMARY KEY,
    [Name] VARCHAR(100) NOT NULL CONSTRAINT UN_DEPARTMENT_NAME UNIQUE,
    [ManagerSsn] SSN_TYPE NOT NULL CONSTRAINT FK_DEPARTMENT_MANAGERSSN FOREIGN KEY REFERENCES EMPLOYEE(SSN),
    StartDate DATE NOT NULL CONSTRAINT DF_DEPARTMENT_STARTDATE DEFAULT GETDATE()
);

SELECT * FROM EMPLOYEE;

DELETE FROM EMPLOYEE
WHERE FName = 'JANE';

UPDATE EMPLOYEE
SET FName = 'JIM'
WHERE Ssn='111111111';

-- INSERT INTO DEPARTMENT VALUES (1, 'Computer Science', '111111111', '2024-10-29');

-- TUPLE ORDERING
SELECT FName, LName
FROM EMPLOYEE
WHERE Salary > 0
ORDER BY FName DESC, LName ASC;

-- UNION, EXCEPT
SELECT * FROM EMPLOYEE
-- WHERE FName = 'RICH'
-- OR FName = 'JIM';
UNION ALL
SELECT * FROM EMPLOYEE
-- WHERE FName = 'JIM';

SELECT * FROM EMPLOYEE
EXCEPT
SELECT * FROM EMPLOYEE
WHERE FName = 'JIM';

SELECT * FROM EMPLOYEE
WHERE FName <> 'JIM';