SELECT ALL FName FROM EMPLOYEE; -- MULTISET.

UPDATE EMPLOYEE
SET FName = 'JOHN'
WHERE Ssn = '111111111';

-- SET OPERATIONS. UNION, EXCEPT, INTERCEPT
SELECT FName FROM EMPLOYEE
EXCEPT
SELECT FName FROM EMPLOYEE
WHERE FName = 'JOHN';

SELECT FName FROM EMPLOYEE
WHERE FName <> 'JOHN';

SELECT * FROM EMPLOYEE
WHERE Salary > 50000
UNION
SELECT * FROM EMPLOYEE
WHERE FName = 'JOHN';

SELECT * FROM EMPLOYEE
WHERE Salary > 50000
OR FName = 'JOHN';

SELECT * FROM EMPLOYEE
WHERE FName = 'JIM'
INTERSECT
SELECT * FROM EMPLOYEE
WHERE Salary > 50000;

SELECT * FROM EMPLOYEE
WHERE FName = 'JIM'
AND Salary >= 50000;

SELECT * FROM EMPLOYEE
WHERE SUBSTRING(FName, 1, 1) = 'J';

SELECT * FROM EMPLOYEE
WHERE FName LIKE 'JI%';

SELECT * FROM EMPLOYEE
WHERE FName LIKE 'J__N';

-- Give me everyone who's salary is between 40000 and 80000 dollars?
SELECT * FROM EMPLOYEE
WHERE Salary >= 40000
AND Salary <= 80000;

SELECT * FROM EMPLOYEE
WHERE Salary BETWEEN 40000 AND 80000;